languageCode = "en-us"
title = "Laurence de Jong"
theme = ["pixyll"]

enableRobotsTXT = true

[indexes]
    tag = "tags"

[params]
    author = "Laurence de Jong"
    keywords = "Laurence de Jong, ldej, Software Engineering, blog, Go"
    description = "A place where Laurence de Jong writes about things."
    ogimage = "/images/ldej.jpg"

[sitemap]
  #changefreq = "monthly"
  filename = "sitemap.xml"
  #priority = 0.5

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    tabWidth = 4
  [markup.goldmark.renderer]
    unsafe = true