languageCode = "en-us"
title = "Laurence de Jong"
theme = ["pixyll"]

[indexes]
    tag = "tags"

[params]
    paginate = 10
    description = "A place where Laurence de Jong writes about things."

[sitemap]
  #changefreq = "monthly"
  filename = "sitemap.xml"
  #priority = 0.5

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    tabWidth = 4
  [markup.goldmark.renderer]
    unsafe = true