languageCode = "en-us"
title = "Laurence de Jong"
theme = ["pixyll"]

[indexes]
    tag = "tags"

[params]
    paginate = 10

[sitemap]
  #changefreq = "monthly"
  filename = "sitemap.xml"
  #priority = 0.5