runtime: go113

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_idle_instances: 1

handlers:
  - url: /api/.*
    script: auto
    secure: always
    redirect_http_response_code: 301

  # index files
  - url: /([^.]+)/$  # urls with no dot in them
    static_files: public/\1/index.html
    upload: public/(.+)/index.html
    expiration: "15m"

  # site root
  - url: /
    static_files: public/index.html
    upload: public/index.html
    expiration: "15m"

  # everything else
  - url: /(.*)
    static_files: public/\1
    upload: public/(.*)